In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Conv2D,  BatchNormalization, MaxPooling2D, Flatten
from tensorflow.keras.datasets import cifar10
from keras.utils import np_utils

In [0]:
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

In [18]:
x_train.shape

(50000, 32, 32, 3)

In [19]:
y_train.shape

(50000, 1)

In [0]:
x_train = x_train/255
x_test = x_test/255

In [21]:
import numpy as np
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [0]:

y_train = np_utils.to_categorical(y_train,10)
y_test = np_utils.to_categorical(y_test,10)

In [23]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [0]:
model = Sequential()
model.add(Conv2D(32, (3,3), activation= 'relu', input_shape = (32,32,3)))
model.add(BatchNormalization())
model.add(MaxPooling2D(2,2))
model.add(Dropout(0.2))
model.add(Conv2D(64, (3,3), activation= 'relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(2,2))
model.add(Dropout(0.3))
model.add(Conv2D(128, (3,3), activation= 'relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(2,2))
model.add(Dropout(0.4))
model.add(Flatten())
model.add(Dense(128, activation= 'relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))
model.add(Dense(10, activation= "softmax"))

In [25]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 30, 30, 32)        896       
_________________________________________________________________
batch_normalization (BatchNo (None, 30, 30, 32)        128       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 15, 15, 32)        0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 15, 15, 32)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 13, 13, 64)        18496     
_________________________________________________________________
batch_normalization_1 (Batch (None, 13, 13, 64)        256       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 6, 6, 64)         

In [0]:
model.compile(loss = 'categorical_crossentropy', optimizer= 'adam', metrics= ['accuracy'])

In [27]:
model.fit(x_train, y_train, batch_size=64, epochs=10 , validation_data= (x_test, y_test))

Epoch 1/10
782/782 [==============================] - 89s 114ms/step - loss: 1.8356 - accuracy: 0.3705 - val_loss: 1.4397 - val_accuracy: 0.4705
Epoch 2/10
782/782 [==============================] - 89s 113ms/step - loss: 1.3825 - accuracy: 0.5047 - val_loss: 1.2576 - val_accuracy: 0.5560
Epoch 3/10
782/782 [==============================] - 89s 114ms/step - loss: 1.2287 - accuracy: 0.5629 - val_loss: 1.0510 - val_accuracy: 0.6289
Epoch 4/10
782/782 [==============================] - 89s 114ms/step - loss: 1.1373 - accuracy: 0.5977 - val_loss: 1.0330 - val_accuracy: 0.6264
Epoch 5/10
782/782 [==============================] - 89s 114ms/step - loss: 1.0779 - accuracy: 0.6201 - val_loss: 0.9518 - val_accuracy: 0.6651
Epoch 6/10
782/782 [==============================] - 89s 114ms/step - loss: 1.0330 - accuracy: 0.6370 - val_loss: 0.8692 - val_accuracy: 0.6985
Epoch 7/10
782/782 [==============================] - 91s 117ms/step - loss: 0.9937 - accuracy: 0.6524 - val_loss: 0.9507 - val_ac

In [28]:
model.evaluate(x_test, y_test)

313/313 [==============================] - 4s 14ms/step - loss: 1.1488 - accuracy: 0.6030


[1.1488151550292969, 0.6029999852180481]

In [29]:
np.argmax(model.predict(x_test) , axis = -1)

array([9, 8, 8, ..., 5, 1, 7])